version: "2.4"
services:
    dotnetsdk:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-dotnetsdk:${VERSION:-latest}
        build:
            context: ./build/dotnetsdk
            args:
                CORE_SDK_IMAGE: ${CORE_SDK_IMAGE}
                DOTNET_SDK_IMAGE: ${DOTNET_SDK_IMAGE}
        scale: 0
         
    solution:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        build:
            context: ../
            args:
                BUILD_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-dotnetsdk:${VERSION:-latest}
                BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
                SOLUTION_BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        scale: 0
        depends_on:
            - dotnetsdk

    mssql:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-mssql:${VERSION:-latest}
        build:
            context: ./build/mssql
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-mssql:${SITECORE_VERSION}
                SPE_IMAGE: ${SITECORE_DOCKER_REGISTRY}modules/spe-assets:${SPE_VERSION}
                #SXA_IMAGE
                #HORIZON_RESOURCES_IMAGE
                #SPS_ASSETS
        volumes:
            - ${LOCAL_DATA_PATH}\mssql:c:\data
        mem_limit: ${MEMORY_LIMIT_SQL:-2GB}
        restart: always

    solr:
        volumes:
            - ${LOCAL_DATA_PATH}\solr:c:\data
        mem_limit: ${MEMORY_LIMIT_SOLR:-1GB}

    id:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id:${VERSION:-latest}
        build:
            context: ./build/id
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-id:${SITECORE_VERSION}
        volumes:
            - ${HOST_LICENSE_FOLDER}:c:\license
        environment:
            SITECORE_LICENSE_LOCATION: c:\license\license.xml
            #hrz_allowed_origin

    cm:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-cm:${VERSION:-latest}
        build:
            context: ./build/cm
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
                SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
                TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
                SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
                #SXA_IMAGE
                #HORIZON_RESOURCES_IMAGE
                #SPS_ASSETS
        depends_on:
            - solution
        volumes:
            - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
            - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
            - ${HOST_LICENSE_FOLDER}:c:\license
        environment:
            SITECORE_DEVELOPMENT_PATCHES: CustomErrorsOff
            SITECORE_LICENSE_LOCATION: c:\license\license.xml
            #Sitecore_Horizon_ClientHost
            #SPS_ClientHost
        entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
        mem_limit: ${MEMORY_LIMIT_SQL:-4GB}

    xconnect:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-xconnect:${VERSION:-latest}
        build:
            context: ./build/xconnect
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xconnect:${SITECORE_VERSION}
                TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
                SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        depends_on:
            mssql:
                condition: service_healthy
            solution:
                condition: service_started
        environment:
            SITECORE_LICENSE_LOCATION: C:\license
        volumes:
            - ${HOST_LICENSE_FOLDER}:C:\license
            - ${LOCAL_DEPLOY_PATH}\xconnect:C:\deploy
        entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"

    xdbsearchworker:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-xdbsearchworker:${VERSION:-latest}
        build:
            context: ./build/xdbsearchworker
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbsearchworker:${SITECORE_VERSION}
                SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        depends_on:
            - solution
        volumes:
            - ${HOST_LICENSE_FOLDER}:c:\license
        environment:
            SITECORE_LICENSE_LOCATION: C:\license

    xdbautomationworker:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-xdbautomationworker:${VERSION:-latest}
        build:
            context: ./build/xdbautomationworker
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbautomationworker:${SITECORE_VERSION}
                SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        depends_on:
            - solution
        volumes:
            - ${HOST_LICENSE_FOLDER}:c:\license
        environment:
            SITECORE_LICENSE_LOCATION: C:\license

    cortexprocessingworker:
        image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-cortexprocessingworker:${VERSION:-latest}
        build:
            context: ./build/cortexprocessingworker
            args:
                BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cortexprocessingworker:${SITECORE_VERSION}
                SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        depends_on:
            - solution
        volumes:
            - ${HOST_LICENSE_FOLDER}:c:\license
        environment:
            SITECORE_LICENSE_LOCATION: C:\license